### ISSUE TITLE
seahash() implementation will not produce correct results

### ISSUE THREAD

**Issue by phgm-d3ab** [rurban/smhasher#104]
During block operation while loop will do 'len -= 32' which means on the [line 119](https://github.com/rurban/smhasher/blob/2cbc8cbf0d98054f6d57d29300bd5337402358d8/seahash.c#L119) len will not have its original value for anything bigger than 32 bytes, so 'a ^= len' in the final state will produce incorrect result.

From the reference:
"Let the final state be (x, y, z, w). Then the final result is given by H = g(x ⊕ y ⊕ z ⊕ w ⊕ l) where l is the number of bytes in the original buffer."

**Comment by rurban** [comment]
Oh, I see. It only taking a few bits from len, not all. Thanks

**Comment by rurban** [comment]
Note: Compare to https://github.com/blainsmith/libseahash/blob/master/src/seahash.c

**Comment by phgm-d3ab** [comment]
that version stores its state in the [seahash_ctx](https://github.com/blainsmith/libseahash/blob/bd9d8f87afb6fbaaf3d43d2967b23d50600eee91/src/seahash.h#L6) which has input_len member, so after processing 32 byte blocks it will do seahash_final() which accesses stored [input_len](https://github.com/blainsmith/libseahash/blob/bd9d8f87afb6fbaaf3d43d2967b23d50600eee91/src/seahash.c#L141) and returns final state

may I suggest something like [this](https://gist.github.com/phgm-d3ab/708e34ffe217d739844de3ba410dc4e5)?

I'm not sure how suitable that would be, if at all; but in my experiments the performance on 1GB of zeroes as well as 1GB of random data was the same (gcc)
note: I did remove seed for those tests
