### ISSUE TITLE
results for bebb4185/discohash

### ISSUE THREAD

**Issue by cris691** [rurban/smhasher#105]
Sorry, I know you've been very busy last week, but could you update the results to include discohash/bebb4185?

unless you're working on making it faster... I'm thinking a merkle tree parallelization like Blake3/Bao

**Comment by rurban** [comment]
Still busy for some time. Care for a PR? I'll just have to run the speed test then.

**Comment by cris691** [comment]
Okay

**Comment by cris691** [comment]
Closed for #107

**Comment by cris691** [comment]
Reopening as results need verification from @rurban

**Comment by rurban** [comment]
Will need a few days. Benchmarking machine buzy with other stuff.
