### ISSUE TITLE
wyhash_v5 release

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#108]
Dear All:
  I am happy to announce wyhash_v5 (https://github.com/wangyi-fudan/wyhash/) with significant contribution from @gzm55
  It come with much speed and security improvement as well as his mad son FastestHash (crazy fast for hash table).
  Please test it and enjoy!
  Wish to see SMHasher benchmark :-) @rurban
Yours
Yi

**Comment by rurban** [comment]
Benchmarks need to wait a few more days, as my benchmarking machine is still buzzy fuzzing another project. But it's indeed faster, and waiting in the `wy5` branch.
I needed to fixup FastestHash a bit. See c04dd4a14ace1147cb9287c6cc7e0d77d88eb454

**Comment by rurban** [comment]
Done with ca178bd58bb0da5a0c9dd44fca34f79a45232686
