### ISSUE TITLE
FastestHash

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#110]
Dear rurban:
  I notice that FastestHash is different from wyhash.h implementation. It is designed carefully in order to be fastest for hashmap. with a different version, it is not optimal for hashmap as shown in your test.
 I take your idea that give a simple seed interface, so will compatiable. 
 FastestHash is not just a toy, it does works.

**Comment by rurban** [comment]
It may work for you, but not for smhasher. With my changes it at least passes some tests

**Comment by wangyi-fudan** [comment]
passing test is one thing, fastest hashmap is another thing.
OK, I know your feeling, my friend... 
Will not talk about it any more. I just want to be fast...
