### ISSUE TITLE
New test: check for read boundaries

### ISSUE THREAD

**Issue by dumblob** [rurban/smhasher#117]
Some recent hashes (e.g. [wyhash gamma](https://github.com/rurban/smhasher/issues/116 )) started to use the technique to read before & behind input boundaries which is in most cases potentially dangerous.

@rurban could we add a test for that? It might be a little tricky as theoretically either an advanced address sanitizer would be needed or at least direct help from the operating system.

**Comment by wangyi-fudan** [comment]
I learnt this one-shot read trick from @erthink 
I guess he is a hacker. He says it will trig warning from security software no mention other problems.
Maybe opertation system leaves some bytes (128bits?) outside the buffer. For example, an AVX load may go across the boundary.
I would like to hear from  @erthink on the consequence of this technology.

**Comment by dumblob** [comment]
It's known, that saving metadata "in front of a buffer" is quite common - i.e. reading there is on many systems OK. Reading data past a buffer is known to sometimes work due to overallocation strategies on many systems.

The problem is, that both behavior are unpredictable, non-standardized, and not guaranteed (not even on those systems in the situation when it worked once, after some time or update or whatever it'll stop working or even do some harm).

So I think it's a nice non-default property of a hash function to gain speed, but I don't think it's wise to make it a default for cross-platform hash function.

Curious what @erthink will say.

**Comment by rurban** [comment]
Good idea, using asan or valgrind.

In practice it depends on the context, if overflows are allowed. similar to if all accesses are aligned. Normally they are not, but sometimes it makes sense to reserve more to get faster hashes.

**Comment by rurban** [comment]
In general we don't want to accept oob (out-of-bounds) hashfuncs. I've added asan and now also ubsan recipes, and all hashes violating these should be labelled poor or unsafe, or not accepted at all.
I've added the asan test to `sanity.sh`

practically such improvements do make sense of course if you can guarantee that the end of tested input buffers never cross a page boundary.

**Comment by dumblob** [comment]
Thanks @rurban ! I think this can be closed then. If not, feel free to reopen.

**Comment by rurban** [comment]
Documentation of UB problems still missing.
Adding it now...

**Comment by rurban** [comment]
Done with 5ec69d6ed9b760c02b1f1f635234ba3f7113dd30
