### ISSUE TITLE
Hash functions with expensive seeding are not handled optimally

### ISSUE THREAD

**Issue by tevador** [rurban/smhasher#128]
I'm testing a custom hash function with very expensive seeding (100 000 cycles to change the seed). Once seeded, the hash function is very fast (~270 cycles/hash). SMHasher is changing the seed frequently, which makes it impossible to complete any tests. I had to resort to hardcoding the seed, which causes the hash function to fail 2 seed-related tests (Seed and PerlinNoise).

Is there a better way to handle expensive seeding in the framework of SMHasher?

**Comment by rurban** [comment]
There is an unmaintained fork, which supports better seeding lengths, esp for 64bit or even 128 and 256bits. But it's a lot of work to include that. See #31

**Comment by tevador** [comment]
I rebased onto your latest commit here: https://github.com/tevador/smhasher/tree/hashx

These tests take hours to complete: "Speed", "Seed", "PerlinNoise". Other tests seem to use a fixed seed value of 0, so they complete normally.

I think at least the "Speed" test could benefit from separating the seeding phase from the actual hashing. Additionally, it would be great to have a way to specify other seed values than 0 for the other tests.

> Do you need to process the IV after each seed change that expensively?

It's expensive because each seed value is generating and compiling a brand new compression function.

**Comment by rurban** [comment]
> It's expensive because each seed value is generating and compiling a brand new compression function.

Oh, now that's interesting! Like the hash jitter.

**Comment by rurban** [comment]
Trying again. Also useful for all streaming or crypto hashes with expensive seeding.
E.g. all the collision tests, but esp. the Hashmap benchmark, which realistucally uses the very same seed throughout.

**Comment by rurban** [comment]
It will not get better than with 86a5892 I'm afraid
