### ISSUE TITLE
Add SM3 hash

### ISSUE THREAD

**Issue by cris691** [rurban/smhasher#129]
SM3 is an official hash of China, based on MD4 and SHA-256

https://github.com/guanzhi/GmSSL/blob/master/crypto/sm3/sm3.c

**Comment by cris691** [comment]
It's developed by the lady who published MD5 collision finding attacks

**Comment by rurban** [comment]
yeah, but it's a crypto hash, so not really urgent. I only added some crypto hashes for comparison purposes. There are many more.

**Comment by cris691** [comment]
okok. I might be able to have a try. would a PR be unwelcome?

**Comment by rurban** [comment]
Welcomed, go ahead. Just feed our seed in, as in the others.

**Comment by cris691** [comment]
OK
