### ISSUE TITLE
Proposing my hash function, should be as good as SHA variants

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#131]
Hello, I've recently come up with the "butterfly effect" PRNG hash - the same concept as `keccak`.

Please consider it for inclusion. Detailed description is here: https://github.com/avaneev/prvhash
32-bit variant does pass SMHasher tests.

Any comments are welcome!

**Comment by rurban** [comment]
Maybe should document that it's a C++ function (due to the default args)

**Comment by avaneev** [comment]
Thanks, I'll remove these. Is "inline" function prefix a problem for a C program?

**Comment by rurban** [comment]
inline is fine. C++ is also fine, but it should be documented. And people tend to prefer C/C++ headers, which can be used in both.

**Comment by avaneev** [comment]
Thanks, I've removed default values.

**Comment by avaneev** [comment]
I think I've tested my hash function with some older smhasher package. hopefully, it passes the newer tests like LongNeighbor, Perlin Noise, Text. I'm unable to compile your latest sources with Intel C++ compiler I use.

**Comment by rurban** [comment]
Oh, that's bad. I'll try to fix that also

**Comment by avaneev** [comment]
I have compiled the latest test suite by removing all hash dependencies and speed tests. My hash functions additionally passes Seed, Text, MomentChi2, PerlinNoise tests. So, a full house, except LongNeighbors which is not included.

**Comment by avaneev** [comment]
I have not tested the Prng as well, since the function fails assert(nbRn < 0) due to some reason on Intel C++ compiler.

**Comment by avaneev** [comment]
I've optimized the function further, and made more tests: now I can say it passes 32-bit and 64-bit tests fully (not including Prng and LongNeighbors as I can't perform these).

**Comment by rurban** [comment]
Extremely slow, but extremely small. Even smaller than FNV1, and it passes most tests.
Thanks, not bad for hash tables, because it's so small.

**Comment by avaneev** [comment]
Thanks, it's not much slower for 4 byte average strings. Which tests it does not pass?

**Comment by avaneev** [comment]
Probably it's better for crypto applications than for hashes. It IS good for PRNG applications with infrequent entropy injections.

**Comment by avaneev** [comment]
64-bit variant can be optimized down to this (taken from `prvrng`), so even faster, without access to hash array:

	inline void prvrng_prvhash42_64( PRVRNG_CTX* const ctx, const uint64_t msg )
	{
	// Entry.

	ctx -> Seed ^= msg;

	// Lower 32 bits of hash.

	ctx -> Seed *= ctx -> lcg;
	uint64_t ph = (uint32_t) ctx -> Hash;
	ctx -> Hash ^= ctx -> Seed >> 32;
	ctx -> Seed ^= ph ^ msg;

	// Upper 32 bits of hash.

	ctx -> Seed *= ctx -> lcg;
	ph = ctx -> Hash >> 32;
	ctx -> Hash ^= ctx -> Seed & 0xFFFFFFFF00000000ULL;
	ctx -> Seed ^= ph ^ msg;

	// Exit.

	ctx -> lcg += ctx -> Seed;
	}

**Comment by avaneev** [comment]
I'll add "optimized" versions in a while. Please call the `prvhash` as prvhash42_64 in you sources, it's important as `prvhash` means arbitrary hash lengths and versions.

**Comment by avaneev** [comment]
I also think your "speed test" is seriously flawed. "Small key speed test" is much more representative.

**Comment by avaneev** [comment]
I've just added `prvhash42opt.h`. Please use functions in this file for speed tests.

**Comment by rurban** [comment]
Done, thanks

**Comment by avaneev** [comment]
Thank you!
