### ISSUE TITLE
PRVHASH again: version 2.5, exponential performance increase.

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#133]
Hi! Sorry to bother you again, but could you re-run the tests with the latest version? Most importantly, the speed tests. It's still called `prvhash42`, because it's only a rearrangement of the same core function. https://github.com/avaneev/prvhash I've discovered this function actually generates pseudo-entropy continuously, shifting from one unrelated state to another, on each entropy injection, so there is no need in N*m operations.

You won't believe it, but now the function creates hashes of any length in O(message_len) time. If possible, please also run 160- and 256-bit function tests, for completeness sake - if your test suite supports such bit lengths.

**Comment by rurban** [comment]
Sure, if I can survive the current heat wave.

**Comment by avaneev** [comment]
Stay safe!

**Comment by avaneev** [comment]
The function is also fast now for any hash length, won't take much of your time.

**Comment by rurban** [comment]
Already running...  speed updates tomorrow.

**Comment by rurban** [comment]
Done

**Comment by avaneev** [comment]
Thanks! But there's more: I've just released `prvhash82` function - it is the same algorithm, but extended to 128-bit math, produces hashes in 64-bit length increments. It's twice as fast as prvhash42, the only drawback is it's not very portable and not very good for short messages. Otherwise it shows exponentially better bit biases in most tests. Maybe you could add `prvhash82_64` and `prvhash82_128` tests?
