### ISSUE TITLE
prvhash42_32 probably uses an old `optimized` version.

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#135]
Please check it out - the benchmark `prvhash42_32` may still use an old verison from `prvhash42opt.h` which is now outdated, I've removed this file as optimized versions are now pointless.

**Comment by avaneev** [comment]
Also note that it is possible to minimize bit biases by adding additional `hl42` term to `int c =` (in `prvhash42`) and `hl84` (in `prvhash82`). This will, however, increase overhead for shorter messages. So, I'm not using this extension by default.

**Comment by avaneev** [comment]
`cycle/map` values also look strange - not different from previous, 2x slower verison of the function.

**Comment by rurban** [comment]
Indeed I'll remove it

**Comment by avaneev** [comment]
An idea on how to further increase the raw speed of the hash function: it should be possible to create a fast fixed-length non-cryptographic hash (which meets most SMHasher requirements on its own, except AppendedZeroes and Zeroes tests) that compresses 16 input byte blocks into 4 hash bytes, that are then sent to PRVHASH input: this may provide an additional 2-3 times speed performance increase. This should still meet the security standards.

**Comment by avaneev** [comment]
Thanks! Note that `prvhash82` cannot be used for 32-bit hashes - it's not a bug, it works only with hash lengths in increments of 8 - 64, 128, 192, 256, etc.

**Comment by avaneev** [comment]
Having 160- and 256-bit verifications could be great as well!
