### ISSUE TITLE
New test: bit frequency normalcy

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#139]
This is a simple test which may be applied to all tests like the bit bias test.

1. 256-element array of `double` counters should be initialized to zero.
2. Take each byte of each resulting hash, and increment counter in 1. based on the byte value.
3. Normalize the counts by dividing by the average count.
4. Sum the resulting square deviations (DEVSQ in Excel), multiply by average count, divide by 256. It should be in some predefined "safe" range: e.g. 0.7-1.3. Too low values are unnatural (e.g. LCG-like randomness) while too high values signal non-uniformity. LCG-like randomness is probably fine, but tells about hash quality.

**Comment by avaneev** [comment]
I actually use this test to generate default seed, it works pretty well. I generate 1 billion bytes with my hash function and evaluate the resulting statistic. Seed that results in 1.0 is pretty good overall.

**Comment by rurban** [comment]
Can you also provide the code for it? Just the basics, no integration needed

**Comment by avaneev** [comment]
```
double Counts[ 256 ] = { 0.0 };

...for all hashes:
uint64_t Hash = <value>;
int j;

for( j = 0; j < 8; j++ )
{
Counts[ (uint8_t) Hash ]++;
Hash >>= 8;
}
... then, finally:
double Avg = 0.0;

for( i = 0; i < 256; i++ )
{
	Avg += Counts[ i ];
}

Avg /= 256.0;
double devsq = 0.0;

for( i = 0; i < 256; i++ )
{
	const double d = Counts[ i ] / Avg - 1.0;
	devsq += d * d;
}

dev *= Avg / 256.0;
```

**Comment by avaneev** [comment]
Here's a complete program to evaluate system RNG.
```
//$ lib "win*|AdvAPI32"

#include <stdio.h>
#include <stdint.h>
#include <math.h>

#if defined( _WIN32 ) || defined( _WIN64 )
	#include <windows.h>
	#include <wincrypt.h>
#else // defined( _WIN32 ) || defined( _WIN64 )
	#define _UNIX 1
#endif // defined( _WIN32 ) || defined( _WIN64 )

#if defined( _UNIX )
	FILE* f; ///< /dev/random file.
#else // defined( _UNIX )
	HCRYPTPROV prov; ///< Crypt provider (for Windows).
#endif // defined( _UNIX )

int main()
{
	#if defined( _UNIX )

		f = fopen( "/dev/random", "rb" );

		if( f == NULL )
		{
			return( 1 );
		}

	#else // defined( _UNIX )

		if( !CryptAcquireContext( &prov, NULL, NULL, PROV_RSA_FULL,
			CRYPT_VERIFYCONTEXT ))
		{
			return( 1 );
		}

	#endif // defined( _UNIX )

	int l;

	for( l = 0; l < 100; l++ )
	{
		double Counts[ 256 ] = { 0.0 };
		uint64_t i;

		for( i = 0; i < ( 1LL << 24LL ); i++ )
		{
			uint8_t val = 0;

			#if defined( _UNIX )

				fread( &val, 1, 1, f );

			#else // defined( _UNIX )

				CryptGenRandom( prov, 1, &val );

			#endif // defined( _UNIX )

			Counts[ val ]++;
		}

		double Avg = 0.0;

		for( i = 0; i < 256; i++ )
		{
			Avg += Counts[ i ];
		}

		Avg /= 256.0;
		double dev = 0.0;

		for( i = 0; i < 256; i++ )
		{
			Counts[ i ] /= Avg;
			double d = Counts[ i ] - 1.0;
			dev += d * d;
		}

		dev *= Avg / 256.0;

		printf( "iter %i dev1 %f\n", l, fabs( 1.0 - dev ));
	}

	#if defined( _UNIX )

		fclose( f );

	#else // defined( _UNIX )

		CryptReleaseContext( prov, 0 );

	#endif // defined( _UNIX )
}
```

**Comment by avaneev** [comment]
Here's also a cool experimental program to find adequate LCG generators. But LCG, of course, fails normalcy test, can't reach 0.8 - 0.12 value range.

[findlcg.txt](https://github.com/rurban/smhasher/files/5106756/findlcg.txt)

**Comment by avaneev** [comment]
If you use only upper 8-bits of such LCG output, it will pass PractRand tests up to 1 GB.

**Comment by avaneev** [comment]
LCG can be easily upgraded to pass beyond 1GB in PractRand. Example LCG which passes 16 GB threshold if upper 8-bits of output are used on each round. (the values were also found via `findlcg.txt` above, but with an added xorshift).
```
const uint64_t lcg1 = 6449002856053061667ULL;
const uint64_t lcg2 = 2168563226064687862ULL;
uint64_t Seed = 9104992244502867339ULL;
...
Seed = Seed * lcg1 + lcg2;
Seed ^= Seed >> 32;
```

**Comment by avaneev** [comment]
This is based on pre-defined seeds, may not work with random seeds. This is not as effective as PRVHASH which outputs random 4 bytes per round, without dependency on the seed value.

**Comment by avaneev** [comment]
@rurban Note that in BitFreq branch you are applying the test to Seed parameter variation. So, this test will only tell how much the hash function is good as a random number generator. The same `bitfreq` test is best applied to the proposed `sparse long` and `Words` tests as well.

**Comment by avaneev** [comment]
@rurban Here is a lot better normalcy estimator. I think all good hash functions pass it anyway, but `fabs( devsq - 1.0 )` has a lot stricter range here, values >0.15 is a fail.
```
init:
	const int BitPoolSizeX = 10;
	const int BitPoolSize = 1 << BitPoolSizeX;
	const int BitPoolSizeMask = BitPoolSize - 1;
	uint64_t BitCounts[ BitPoolSize ] = { 0 };
	int BitPoolPos = 0;

update:
		int j;

		for( j = 0; j < HashLen; j++ )
		{
			uint8_t v = Hash[ j ];
			int k;

			for( k = 0; k < 8; k++ )
			{
				BitCounts[ BitPoolPos ] += v & 1;
				BitPoolPos = ( BitPoolPos + 1 ) & BitPoolSizeMask;
				v >>= 1;
			}
		}

final:
	uint64_t AvgI = 0;

	for( i = 0; i < BitPoolSize; i++ )
	{
		AvgI += BitCounts[ i ];
	}

	double Avg = (double) AvgI / BitPoolSize;
	double devsq = 0.0;

	for( i = 0; i < BitPoolSize; i++ )
	{
		const double d = BitCounts[ i ] / Avg - 1.0;
		devsq += d * d;
	}

	devsq *= 2.0 * Avg / BitPoolSize;
```

**Comment by avaneev** [comment]
@rurban Here's a lot better variant, works better since bit buffer length is a prime number.

init:
	const int BitPoolSize = 1021;
	uint64_t BitCounts[ BitPoolSize ] = { 0 };
	int BitPoolPos = 0;

update:
		int j;

		for( j = 0; j < HashLen; j++ )
		{
			uint8_t v = Hash[ j ];
			int k;

			for( k = 0; k < 8; k++ )
			{
				BitCounts[ BitPoolPos ] += v & 1;
				BitPoolPos++;
				
				if( BitPoolPos == BitPoolSize )
				{
					BitPoolPos = 0;
				}

				v >>= 1;
			}
		}
