### ISSUE TITLE
New hash: What name?

### ISSUE THREAD

**Issue by thomasahle** [rurban/smhasher#153]
I have implemented tabulation hashing, but the mixing step is multiply-shift and polynomial hashing.
Should I submit it as "tabulation" or just replace multiply_shift, since the current implementation isn't very good anyway?

**Comment by rurban** [comment]
I would call it tabulation (3-indep), and keep multiply_shift as is. It's a theoretical hash for different purposes anyway.

**Comment by thomasahle** [comment]
Yeah, it's just that none of them are a variable length string hash.. Multiply shift is a fixed length string hash and tabulation is a finaliser. Only by combining them (and with variable length polynomial hashing too) do we actually get a hash that makes sense in the setting of smhasher.

But as long as you are fine with it not being "only" tabulation, I'll use that name 😊

**Comment by rurban** [comment]
Maybe mult_w_tabulation "mult with tabulation finalizer" then
