### ISSUE TITLE
Remove "UB" and "insecure" from poly and tabulation hashes

### ISSUE THREAD

**Issue by thomasahle** [rurban/smhasher#156]
The current versions of poly and tabulation hashing (and multiply-shift) handle proper memory alignment, so they no longer need the UB tag.

They also finalize properly, which kills the "extension" attack.

**Comment by rurban** [comment]
The next step to learn would be to file a pull request :)

**Comment by thomasahle** [comment]
I thought that would be too aggressive if you didn't agree :-)

**Comment by rurban** [comment]
Yeah, indeed I disagree a bit.
The three families *multiply_shift, poly_X_mersennes and tabulation still cancel itself out.
You can check that by:
Add the computed Verification value to main.cpp, recompile and verifiy again. The new Verification value turns 0.

I also needed to change all doc/*.html docs. Done with 4751ea814177d97db29eb1fe4619cf366a71b8e5

**Comment by thomasahle** [comment]
I computed the verification for tabulation (0xC4E7B650) and added it to main.cpp. It not turned 0x36E6223B, not zero. 
I also added the verification value for poly_2 and recompiled. It didn't change its verification value.

**Comment by thomasahle** [comment]
You seem to suggest that h(x, h(x)) should equal 0. I fail to see how you get to this result.

The closest I can get is this: if the hash function was simply the polynomial "x0 + x1 a + x2 a^2" and an attacked knew the value of "y = x1 a + x2 a^2" and of "a", then they could set "x0 = - a y" to get a zero value.

However, the attacked doesn't know "a", and the hash functions don't function like this. There is no easy way to find "y" from the final hash value.

**Comment by thomasahle** [comment]
@rurban I want to fix this, but I honestly need more help understanding the problem. I tried the verification thing you mentioned, and it didn't work/cancel.

**Comment by rurban** [comment]
I stated writing some wiki pages for this

**Comment by thomasahle** [comment]
Awesome!
I discovered why VerifyAll is giving those zero values: Hash_seed_init in main.cpp isn't actually doing anything. The "if (true)" should be "if (false)". Changing that fixes the problem. I can send a pull request tomorrow.

**Comment by rurban** [comment]
Uuh

**Comment by rurban** [comment]
Nope, you are wrong. You were disabling the seed init.

**Comment by thomasahle** [comment]
Please check it again. It is correct.
You can see that without this patch tabulation and poly_k gave 0 for all hash values.
With this patch all vaues are different and they pass verification.

**Comment by rurban** [comment]
But then Hash_seed_init is never called. Your patch bypassed it.

Thomas Dybdahl Ahle <notifications@github.com> schrieb am Mo., 21. Sep.
2020, 15:47:

**Comment by thomasahle** [comment]
No, the other way around. It was bypassed before (a bug I introduced a while ago I'm afraid), but the patch re-enables it.

**Comment by rurban** [comment]
Will check tomorrow

**Comment by rurban** [comment]
Indeed. sorry that was the probem. Will remove the wrong tags now

**Comment by thomasahle** [comment]
Awesome! 😁
Thanks for all the effort you put into this project.
