### ISSUE TITLE
Absolute results are wrong

### ISSUE THREAD

**Issue by vegorov1** [rurban/smhasher#16]
Looking at timing again, it's all off. E.g. FNV-1a has one IMUL (3 cycles latency) and one XOR (1 cycle latency) applied serially on each byte. It just can't be faster than 4 cycles per byte. Time stamp counter in newer processors is time-based, it increments on constant rate that doesn't change when CPU boosts its frequency, it doesn't depend on CPU state. So RDTSC doesn't measure real cycles passed anymore, and benchmark can report speed in cycles faster than it really executes. On my desktop 3.5GHz Haswell CPU (3.8GHz with TurboBoost), reported speed is 1-3.5/3.8=8% faster than real speed. On laptops it's apparently far more different.

"MiB/sec @ 3 ghz" is entirely wrong too. It's just the result of multiplication (bytes/cycle) \* 3*10^9 / 1024^2, but bytes/cycle is wrong.

So while _relative_ benchmark results are sensible and useful, absolute results are incorrect.

**Comment by rurban** [comment]
Agreed. Maybe use some synthetic cachegrind metric to display the absurd throughput in bytes/cycles

**Comment by vegorov1** [comment]
Apparently SMHasher also doesn't work on ARM, timing code is x86-only.

I'm thinking about just importing all the timing code from Google Benchmark. It has code to measure both time and CPU frequency: https://github.com/google/benchmark/blob/master/src/cycleclock.h https://github.com/google/benchmark/blob/master/src/sysinfo.cc etc.

It uses Apache 2.0 license. What do you think?

**Comment by rurban** [comment]
Yes. As git submodule it would be easier to maintain, but it's too big for that.

**Comment by rurban** [comment]
I've fixed that now with proper benchmarking from
https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/ia-32-ia-64-benchmark-code-execution-paper.pdf, the Improved Intel Benchmarking Method.
serialize with cpuid and rdtscp, split into timer_start() and timer_end() in b93bccb026eca003c9a49e4777790ec09f54cf34

**Comment by leo-yuriev** [comment]
I can make a PR with mera library. Would you like?

**Comment by rurban** [comment]
Not really, only optionally for ARM or other non-Intel platforms. 
I'd rather keep it simple and down to the bones. 
I only want to get the actual CPU clock speed later, from cmake e.g.
