### ISSUE TITLE
Bus error on BEBB4185

### ISSUE THREAD

**Issue by thomasahle** [rurban/smhasher#160]
When building and running SMHasher on mac with `--test=VerifyAll`, I get a `bus error` crash after testing SipHash:
```
$ build/SMHasher --verbose --test=VerifyAll
[[[ VerifyAll Tests ]]]
           ...
           SipHash13 - Verification value 0x29C010BF ....... PASS
[1]    83740 bus error  build/SMHasher --verbose --test=VerifyAll
$
```
I tested this on master as well as 4751ea814177d97db29eb1fe4619cf366a71b8e5.

**Comment by rurban** [comment]
So maybe Siphash needs an UB tag also. But I'll rather want to fix it. Will not have time to check this until Monday

**Comment by thomasahle** [comment]
It could also be related to issue #162 I guess.

**Comment by thomasahle** [comment]
If I comment out "BEBB4185 64" in `main.cpp`, SMHasher runs to completion.

**Comment by rurban** [comment]
@chris691 you need to test it with ubsan
