### ISSUE TITLE
Verification test hashes with length=0

### ISSUE THREAD

**Issue by thomasahle** [rurban/smhasher#162]
In this line presumably we'd want `hash (key,i+1,256-i,&hashes[i*hashbytes]);` rather than `hash (key,i,256-i,&hashes[i*hashbytes]);`, since hashing 0 bytes doesn't make much sense.
https://github.com/rurban/smhasher/blob/d8caf64e1332c90d563b82e7bc76fc7695ddaf74/KeysetTest.cpp#L37
This will change all the verification values though, so I don't know if it's worth the effort.

**Comment by rurban** [comment]
No, I rather want to keep the handling of special case of len=0 in the verification value. if it returns 0 or some constant.
