### ISSUE TITLE
Allow 8x collisions for expected values < 0.5

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#165]
From my practice, sometimes, but not often, the hash function may produce 2 collisions with expected 0.3 collisions. This probably happens due to rounding. E.g. 0.3 * 4 = 1.2 which sometimes can give 2 collisions. Your current limit is 4x for expected values < 10.

**Comment by rurban** [comment]
1.2 is still lower than 1.5 which will round to 2. And 1.2 for the range 0.3 to 1.5 looks good to me. Admitted, with such low numbers N=10 the variance is much higher, but 8x sounds excessive to me. All the good hashes pass this test.

**Comment by avaneev** [comment]
Maybe I'm not totally correct, but in some very rare cases 2 is still possible with expected 0.3 (mainly in Sparse tests).

**Comment by avaneev** [comment]
@rurban The problem is, with the latest version of my hash function, in Sparse 16-bit test the bias may go as low as 0.550% yet there sometimes can be 2 collisions in low or high 32-bits. All other tests pass fine. Which makes me think it's really is a problem of expectations rounding.

**Comment by avaneev** [comment]
@rurban Alternatively, you can just change the comparison criterion: instead of comparing collisions to `expected value * 4`, compare it to `(int) ceil( expected_value * 4 )` which looks pretty logical.

**Comment by rurban** [comment]
OK, that looks better indeed

**Comment by rurban** [comment]
Done with 483217bb5175fab82451f7a50e5ea943d11af3d5
