### ISSUE TITLE
Blake3_c seed inclusion error (might be causing the seeding issues)

### ISSUE THREAD

**Issue by bharrisau** [rurban/smhasher#168]
https://github.com/rurban/smhasher/blob/c91d5385d581ce21629a5b677e0a36cac2378ef6/Hashes.h#L978

Existing
```C
inline void blake3c_test ( const void * key, int len, unsigned seed, void * out )
{
    blake3_hasher hasher;
    blake3_hasher_init (&hasher);
    // mix-in seed. key0 is not enough to pass MomentChi2. but even mixing all does not help
    //for (int i = 0; i < 8; i++)
    //  hasher.key[i] ^= (uint32_t)seed;
    hasher.key[0] ^= (uint32_t)seed;
    blake3_hasher_update (&hasher, (uint8_t*)key, (size_t)len);
    blake3_hasher_finalize (&hasher, (uint8_t*)out, BLAKE3_OUT_LEN);
}
```

The code tries to init the seed by updating `hasher.key[0]`. The problem is that `hasher.key[0]` is only used to update `hasher.chunk.cv[0]`, and `cv` is used internally in the hash function. This should result in the first block of data entered into the has function ignoring the seed and using default IV, but after the function calls 'reset' internally the seeded hash will be used from then on.

```C
blake3_hasher_init (&hasher);
// Calls: hasher_init_base(self, IV, 0)
// Which calls: chunk_state_init(&self->chunk, key, flags)
// Which calls: memcpy(self->cv, key, BLAKE3_KEY_LEN)
```

The code needs to be one of the following (I'm writing it in GitHub, so might not be correct C).

```C
//  hasher.key[i] ^= (uint32_t)seed;
hasher.key[0] ^= (uint32_t)seed;
hasher.chunk.cv[0] ^= (uint32_t)seed;  // Added
blake3_hasher_update (&hasher, (uint8_t*)key, (size_t)len);
```

Or else

```C
inline void blake3c_test ( const void * key, int len, unsigned seed, void * out )
{
    uint32_t seed_key[8] = {0x6A09E667 ^ (uint32_t)seed, 0xBB67AE85, 0x3C6EF372,
                               0xA54FF53A, 0x510E527F, 0x9B05688C,
                               0x1F83D9AB, 0x5BE0CD19};  // Copied the default IV from blake3_impl.h
    blake3_hasher hasher;
    blake3_hasher_init_keyed(&hasher, (uint8_t*)seed_key);  // Changed to the KEYED variant

    blake3_hasher_update (&hasher, (uint8_t*)key, (size_t)len);
    blake3_hasher_finalize (&hasher, (uint8_t*)out, BLAKE3_OUT_LEN);
}
```

**Comment by rurban** [comment]
Oh thanks. I'll test if the 2nd option, which looks much better, is fast enough.

**Comment by bharrisau** [comment]
Ok - just in case it matters - using `blake3_hasher_init_keyed` will result in different hashes than the other method. It uses a different `domain separation bit flags` (called `d` in the Blake3 spec). It is `KEYED_HASH` or 0b0001_0000 defined in `blake3_impl.h`.

The default mode uses 0 for the flag, and there is also a `DERIVE_KEY` mode which uses different flags.

I don't think it should matter for this use case, just wanted to point it out for completeness.

**Comment by rurban** [comment]
Thanks, this was it. It fixed all the blake3_c issues. Just the 32bit verifier is still different.
