### ISSUE TITLE
PRVHASH64_64M

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#175]
After more research on what I've got with PRVHASH, I've come up with a "minimal" implementation, which is good for table hash use. It's the smallest high-quality 64-bit hash function with good security in existence I think (420 bytes in x86_64 clang 11, -O2). It passes SMHasher tests. Please include it to your test suite.

https://github.com/avaneev/prvhash

**Comment by rurban** [comment]
prvhash42m_32, right?

**Comment by avaneev** [comment]
> prvhash42m_32, right?

Yes, this is right, thank you!

**Comment by avaneev** [comment]
@rurban I've added a fix when MsgLen==0, and removed if( Msg < MsgEnd - 7 ) case which reduced code size by further 15-25 bytes without much speed impact.

**Comment by avaneev** [comment]
Made an additional adjustment to the function - it decreased code size in GCC (which previously unrolled it anyway). But in LLVM compilation the size did increase. This change also increased "small hash" performance quite a bit.

**Comment by rurban** [comment]
Check #179. Ensure to update the sizes

**Comment by avaneev** [comment]
Updated to v3.1, function's size is now below 380 bytes.

**Comment by rurban** [comment]
Done, just prvhash16 will be added later eventually
