### ISSUE TITLE
wyhash compiled size

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#176]
Dear rurban:
  I am finishing wyhash paper with pushes from industry.
  I can not calculated the compiled size of hash function unless copying from your website.
  Current wyhash size is for the final_version_1. I guess the final_version_2 size is smaller.
  Would you update this number for me?
  Many thanks!

**Comment by avaneev** [comment]
You can estimate at godbolt.org for the given compiler - enable the compile to binary option.

**Comment by wangyi-fudan** [comment]
> You can estimate at godbolt.org for the given compiler - enable the compile to binary option.

i got 344 bytes by godbolt.
however, to make a fair comparision with other hash functions, I would like to hear from smhasher

**Comment by avaneev** [comment]
It depends on compiler options (smaller code for -Os or -O1, larger of -O3), and actual inlining/unrolling. In production it can be twice as large, depending on what compiler decides. So not too great an estimate anyway. It's actually even usually hard to find start/end of a function from binary output and what godbolt shows.

**Comment by rurban** [comment]
Ok, will do.

**Comment by avaneev** [comment]
> i got 344 bytes by godbolt.
> however, to make a fair comparision with other hash functions, I would like to hear from smhasher

You've beaten my latest "minimal" hash function by about 10 bytes. However, I focus on security, and did a fair bit of research on this - but until it's published an peer-reviewed, of course, these are just author's claims.

**Comment by rurban** [comment]
Done. Indeed only half the size from last time.
Default amd ryzen3 -march-native without AVX512, lto -O3 gcc-10
