### ISSUE TITLE
add t1ha hash (fastest, pass all tests)

### ISSUE THREAD

**Issue by leo-yuriev** [rurban/smhasher#18]
ready = https://github.com/leo-yuriev/t1ha/tree/smhasher-rurban.t1ha

**Comment by rurban** [comment]
Thanks, looks good

**Comment by rurban** [comment]
Merged, thanks. I just had no room for your README.md docs. Maybe put them into the header.

**Comment by leo-yuriev** [comment]
Sorry, but I just updated t1ha.
This is a fairly important change.

In general, I was switched to little bit faster 'mux' version (with 64x64 mul) and to C from C++.
But also fixes a possibility of crossing page boundary at the end of key, in case it was unaligned.
This is not a flaw in case using t1ha in the 1Hippeus project, but seriously bug for general hash function.

Please merge again.

**Comment by rurban** [comment]
Can you add the t1ha_mux variant also? 
This is now missing from your smhasher-rurban.t1ha branch

**Comment by leo-yuriev** [comment]
It was decided to leave only the "mux" variant, at the same time renaming it into "t1ha".
Maybe it's not the best solution, but in general should be better.

I think, I should clarify:
- The 'mux' version (which now called as main "t1ha") is faster for small keys, but same speed for large keys.
- The old version (originally called 1Hippeus Hash) was dropped, because it should be fixed/refined against flaw that I noted.
- This should not be mislead about "t1ha" name, because it just published as "Positive Hash" and it have not been used before.

https://github.com/leo-yuriev/t1ha/blob/smhasher-rurban.t1ha/main.cpp#L184

**Comment by rurban** [comment]
But this would not work on 32bit then. No plan for a 32bit version?

**Comment by leo-yuriev** [comment]
It should already work. More over, and much faster than mum-hash.

I implemented the required multiplication for the absence of __int128.

**Comment by leo-yuriev** [comment]
It should already work. More over, much faster than mum-hash.

I implemented the required multiplication for the absence of __int128.

**Comment by rurban** [comment]
Great

**Comment by rurban** [comment]
This looks like a bug:
```
add_with_carry(uint64_t *sum, uint64_t addend) {
  *sum += addend;
  return sum < addend;
}
```
=>
  `return *sum < addend;`

and it is also invalid C++ with -fpermissive

**Comment by leo-yuriev** [comment]
Oops. Sure this is bug. Just lost de-referense while conversion from C++ to C.

It is question for QA. How it passes the tests?

**Comment by rurban** [comment]
I was QA. I didn't pass :)

in smhasher it just added randomly a 0 or 1 to it, which apparently qualifies as good enough.

**Comment by leo-yuriev** [comment]
;)

+1

I am on the road approximately two hours.

**Comment by leo-yuriev** [comment]
Thank!
