### ISSUE TITLE
Fix PRVHASH64 and PRVHASH64S speeds

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#181]
I've noticed that the table lists PRVHASH64 as having 2.3GB/s and 50 cycles while in the benchmark file the speed is 4.3 GB/s and 37 cycles. Same for PRVHASH64S - 9.8GB/s and 129/160 cycles.

**Comment by avaneev** [comment]
@rurban Will you update the speeds? The speeds in the table to dot reflect speeds in the text file. For other hashes they reflect them, why the difference? You may also re-benchmark speeds on PRVHASH 3.3 - it's about 5% faster than 3.2.

**Comment by rurban** [comment]
Ok, will have a look

**Comment by rurban** [comment]
Aleksey Vaneev ***@***.***> schrieb am Di., 30. März 2021,
19:10:

> @rurban <https://github.com/rurban> Will you update the speeds? The
> speeds in the table to dot reflect speeds in the text file.
>
I just forgot to fixup the speeds. Done already.

For other hashes they reflect them, why the difference? You may also
> re-benchmark speeds on PRVHASH 3.3 - it's about 5% faster than 3.2.
>

Ok, will do after the BadSeeds search. This needs quite a lot if CPU

**Comment by rurban** [comment]
Updated with ae49d37ac710f6f51cfcd338b6a4ec2f88a4add8
