### ISSUE TITLE
Is metrohash not stable across platforms ? 

### ISSUE THREAD

**Issue by rohitva** [rurban/smhasher#184]
Hi,

I found [metrohash128crc.cpp](https://github.com/rurban/smhasher/blob/b49c944f84dfc540ca20272266e9f844ab0222a7/metrohash128crc.cpp) and [metrohash128.cpp](https://github.com/rurban/smhasher/blob/b49c944f84dfc540ca20272266e9f844ab0222a7/metrohash128.cpp) generates different hash values for the same input key. Is that expected ? 
I am seeing different hash output for a key on `x86_64` vs `ARM` machine and want to understand if that's expected or not. 

Thanks,
Rohit

**Comment by rohitva** [comment]
Hi All,

Can someone help on it ? 

Thanks,
Rohit

**Comment by rurban** [comment]
This is interesting, because I thought `sse2neon.h` crc intrinsics do the very same
