### ISSUE TITLE
crc32c_pclmul_test measuring no-ops when key is aligned

### ISSUE THREAD

**Issue by nigeltao** [rurban/smhasher#189]
[`crc32c_pclmul_test`](https://github.com/rurban/smhasher/blob/d356fd967b6120ccaf0b26579710e2d9faacc70a/Hashes.h#L91-L119) in `Hashes.h` is:

```c
inline void crc32c_pclmul_test(const void *key, int len, uint32_t seed, void *out) {
  if (!len) {
    // Blah blah.
    return;
  }
#ifdef NDEBUG
  if (((uintptr_t)key & 15) != 0) {
    // Blah blah call crc32_pclmul_le_16.
  }
#else
  assert(((uintptr_t)key & 15) == 0); // input must be 16byte aligned
  // Blah blah call crc32_pclmul_le_16.
#endif
}
```

By default, `NDEBUG` is defined, which means that the `#else` path is **never taken**, which means that `crc32c_pclmul_test` is (incorrectly) **a no-op when key is 16-byte aligned**.

The "crc32_pclmul 1972140.38 MiB/sec" table cell in the top level `README.md` file is a mis-measurement.

**Comment by rurban** [comment]
!!!! That's the explanation, whow.

**Comment by rurban** [comment]
crc32_pclmul requires a key alignment of 16, and a minimum len of 64, which we violated.
fixing it.

**Comment by rurban** [comment]
Yes, now the numbers looks much more than yours. Thanks!
