### ISSUE TITLE
UB reproducibility 

### ISSUE THREAD

**Issue by i5ik** [rurban/smhasher#191]
Hey @rurban 

Thanks a lot for your work on SMHasher. It's really changed a lot in the last 3 years, all because of the effort you put in. The project's so much bigger than it was before, and better, thanks to your effort. I, and I'm sure a lot of others, really appreciate what you're doing.

Anyway, I'm sure you're super busy so I get if you can't get to this, or if anything makes it impossible for you and that's cool, everyone's got different degrees of freedom there, but I was just wondering about something and I have a pretty stupid question so I'm sorry.

Question is: how do I reproduce the "UB" claims you make against some of the hashes? Specifically I'm trying to repro on my hashes discohash and beamsplitter so I can try to address the UB flags you put against them. I tried,

```console
$ clang++ -fsanitize=undefined *.cpp
```
on my discohash repo and it compiled fine. Sorry I'm not an expert in this and I know it's not your job, so if you can't reply that's cool. I'm just wondering, how do I do it like you did it so I can reproduce the behaviour you're seeing?

Anyway, I get if you're too busy to reply or if anything else means you can't get to this and that's cool, everyone has different degrees of freedom there,  I wish you all the best in SMHasher and have a great 2021!

Cris

**Comment by rurban** [comment]
ubsan is a runtime check!

**Comment by i5ik** [comment]
Do you know how i can reproduce it so i can see where the check is erroring?

**Comment by i5ik** [comment]
If you know how i can reproduce it so i can see where the check is erroring, and you let me know, I'll probably work on a fix.

**Comment by i5ik** [comment]
If you know how I can reproduce the behavior you're seeing and you let me know how to do that I might work on a fix.

**Comment by i5ik** [comment]
If you know how I can reproduce the behavior you're seeing and you let me know how to do that I might work on a fix.

**Comment by rurban** [comment]
Use the Debug CMAKE_BUILD_TYPE and run smhasher with your hash.
```sh
mkdir Debug
cd Debug
cmake .. -DCMAKE_BUILD_TYPE=Debug
make
./SMHasher BEBB4185
```

If the UB is fixed in-between please file a ticket.

**Comment by i5ik** [comment]
Thankyou @rurban ! ☺️
