### ISSUE TITLE
Add NMHASH32X variant of NMHASH32

### ISSUE THREAD

**Issue by gzm55** [rurban/smhasher#194]
`NMHASH32X` is a variant of `NMHASH32`, which mixes short keys with 32x32->32 `MUL`, and improve the speed of short keys.

https://github.com/gzm55/hash-garage/blob/master/nmhash.h#L712

**Comment by gzm55** [comment]
@rurban

notes of this update:
- the original `NMHASH32` is unchanged
- do not depend on c style union initialization
- add NMHASH32X variant, using the low half 32bit mul in invertible mixers, the speed for short keys should be nearly the same as that of xxhash32

**Comment by gzm55** [comment]
@rurban it is strange that the verify code is not portable, i will check that.

**Comment by rurban** [comment]
It varies even from clang 10.0.1 to 10.0.0 on linux (Fedora vs Ubuntu)

**Comment by gzm55** [comment]
the endian and UB bug should be fixed in latest commit a8913138bdb3b7539c202edee30a7f0794bbd835

**Comment by rurban** [comment]
Yes, this fixed it. A good one
