### ISSUE TITLE
crc32c_pclmul segfaults on Linux (CentOS 8)

### ISSUE THREAD

**Issue by benmenadue** [rurban/smhasher#195]
Commit 127db355f683b4c0ab3dd1f43267398510e35f19 changed which aligned allocation function gets used with for `crc32c_pclmul` under GCC 8.3.1 (i.e. CentOS 8) from `aligned_alloc` to `posix_memalign` because `__STDC_VERSION__` is not defined there when compiling C++ code. 

https://github.com/rurban/smhasher/blob/e09d0cd2ec139ed118d52b690d2cfba20399f8af/Hashes.cpp#L1180-L1187

However, `posix_memalign` returns the status, rather than the pointer to the region, and so this causes a segfault in the `memcpy` immediately following as `input` will be `0` (meaning "success").

**Comment by gzm55** [comment]
```diff
-      alignas(16) unsigned char const *input = (unsigned char const *)posix_memalign((void**)&key, 16, len);
+      alignas(16) unsigned char const *input = 0;
+      posix_memalign((void**)&input, 16, len);
```

**Comment by rurban** [comment]
Oops, thanks. I didn't test it
