### ISSUE TITLE
UB: in PerlinNoiseTest memcpy may read more bytes than source variable

### ISSUE THREAD

**Issue by gzm55** [rurban/smhasher#198]
https://github.com/rurban/smhasher/blob/6eb697f628643fdfcaefbcf0a7d228f84eac80e1/KeysetTest.h#L305

here `x` is of type `int`.

**Comment by rurban** [comment]
Thanks, inputLen is max 16. 
I don't want to support uint128_t in this loop, so I'll delete the 16 part, and enhance int to uin64_t.
