### ISSUE TITLE
PCLMULQDQ optimization missing

### ISSUE THREAD

**Issue by ysangkok** [rurban/smhasher#2]
See http://www.intel.com/content/dam/www/public/us/en/documents/white-papers/fast-crc-computation-generic-polynomials-pclmulqdq-paper.pdf

**Comment by rurban** [comment]
Thanks. Isn't that what zlib does (crc32_hw1.c)? I thought so, but apparently not.

**Comment by ysangkok** [comment]
It's not the crc32 instruction if that's what you mean. See also https://crc32c.angeloflogic.com/performance/ I don't think it's in the official zlib, but it has been added to an Intel fork: https://github.com/jtkukunas/zlib/commit/3684659f485b63f7482a8dc600f51112c556ce9d

**Comment by rurban** [comment]
I'll be using cloudflare's zlib fork as submodule. https://github.com/cloudflare/zlib/

**Comment by Bulat-Ziganshin** [comment]
there are faster CRC32 implementations,
reaching 1 byte/cycle depending on compiler smartness

see https://github.com/Bulat-Ziganshin/Crc32
or http://create.stephan-brumme.com/crc32/

the same algo is also implemented in Google crcutil library,
in  much  more  generic  way  - 1 cycle/byte for any CRC32/64,
1.7 for crc128

**Comment by troosh** [comment]
Look to https://github.com/intel/soft-crc also.

**Comment by paulie-g** [comment]
This is a tricky proposition - it's available (but very slow) on pre-Haswell/Jaguar, something like 7-8 cycles vs 2 on Haswell and later.

**Comment by rurban** [comment]
In the meantime I've added the crc32_pclmul hash, which is really fundamentally faster.
