### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by atdt** [rurban/smhasher#201]
The original SMHasher was [released under under the MIT license](https://github.com/aappleby/smhasher/blob/master/README.md). Is this fork also MIT-licensed? I don't see a project-level license anywhere. Could you please clarify?

**Comment by rurban** [comment]
Sure it's MIT also. Let me check...

**Comment by rurban** [comment]
Done. Haven't summarized each individual hash licenses. You need to look them up by yourself.
