### ISSUE TITLE
Warning for reads past the end of a page

### ISSUE THREAD

**Issue by michaeleisel** [rurban/smhasher#206]
In https://github.com/rurban/smhasher/issues/75 , it's pointed out that Pippip_Yurii can cross page boundaries into unowned memory, and a warning is added for it. I think it'd be good if this warning was added for other functions with the same problem, such as FNV1A_Totenschiff. It also might be good to add a note for these functions in "Quality Problems" in the benchmarks.

**Comment by rurban** [comment]
Agreed

**Comment by rurban** [comment]
These hashes are all marked as UB, with the description including oob.
