### ISSUE TITLE
komihash - Very Fast Non-Cryptographic Hash Function

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#215]
It's my answer to wyhash. It may be a bit slower than wyhash, but structurally it's much more reliable, should not have any "bad seeds". Unusable for PerlinNoise with seed > 32-bits. Other than that, it seems to pass all SMHasher tests.

https://github.com/avaneev/komihash

**Comment by dumblob** [comment]
>Unusable for PerlinNoise with seed > 32-bits.

This caught my full attention. Does this mean smhasher is so "gappy" that its results can miss given hashes usability for perlin noise? Could you clarify what does it actually mean "unusable with perlin noise" (I couldn't find anything in your repo about how you measured the "level of usabillity")? Shall we add perlin noise test to smhasher?

**Comment by avaneev** [comment]
PerlinNoise test in SMHasher is rather limited - it scans through a limited bit range. `komihash` will definitely fail PerlinNoise test if it used a seed beyond 32-bit range - the message and seed may simply overlap in that case. I assume this is fixable in `komihash`, but at some overhead only.

**Comment by dumblob** [comment]
I didn't look at komihash yet, but how about constraining the hash to accept only 32bit seeds? Btw. it sounds like it maintains only 32bit state internally which will harm its quality... I'm curious what @rurban's test machine will say.

**Comment by avaneev** [comment]
`komihash` is fully 64-bit, but SMHasher's seeds are 32-bit indeed, so no way to detect issues.

**Comment by avaneev** [comment]
I think SMHasher could "upgrade" seeds to 64-bit and additionally use a bit more sparse seeds in PerlinNoise test (e.g. stretch 16-bit value to 64-bit value by inserting bits).

**Comment by avaneev** [comment]
I've actually now fixed possible issues with PerlinNoise, even if previously undetected by SMHasher, but at a minor overhead.

Anyway, PerlinNoise test's limitations still exist.

**Comment by rurban** [comment]
Yes, my smhasher has a limited 32bit seed only. In reality you can/should pass much longer seeds, from 64bit to 256 bits.
But these cannot be tested then, brute-force computable are only 32bit.

**Comment by rurban** [comment]
Added, thanks
