### ISSUE TITLE
New test: hash function branching

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#217]
I think this may be a useful test. Many hash functions use different "paths" when handling various hash lengths. This test tries to catch collisions between these "paths", plus it's at the same time an additional "zeroes"-like test.

```
uint64_t msg[ 16 ] = { 0 };

for( int k = 0; k < 80000; k++ )
{
	msg[ 0 ]++;

	for( int i = 8; i <= 128; i++ )
	{
		h = hash( (uint8_t*) &msg, i, seed );
	}
}
```

**Comment by avaneev** [comment]
@rurban `mum` fails the test, so a useful test it seems.

**Comment by avaneev** [comment]
@rurban ah, my mistake. it is new perlinnoise which `mum` does not pass. this test does not seem to work that well. you may not implement it if in your tests you can't find any broken hash functions.

**Comment by rurban** [comment]
But you still need to be a bit more explicit. I dont see what value needs to be tested, what is good and what is bad. Maybe a PR?

**Comment by avaneev** [comment]
Well, I'll need to think about this test further, maybe try to find some "resonant" numbers or patterns like I did in that new PerlinNoise test.

**Comment by avaneev** [comment]
As for the PR, sorry it's not available to me - I'm using LLVM8 and had to strip a lot of things from SMHasher, it does not compiler otherwise. Unfortunately, no good GCC compiler for Windows.
