### ISSUE TITLE
fix mingw build

### ISSUE THREAD

**Issue by rurban** [rurban/smhasher#224]
See the actions runner. Some hashes are not yet mingw compatible.
I don't have a windows machine anymore.

**Comment by rurban** [comment]
Fixed somehow

**Comment by tansy** [comment]
> I don't have a windows machine anymore.

You can use native mingw compiler with wine. Msys is also helpful.
```
$ cd path/to/msys
$ wine cmd
\> msys.bat
$ gcc
gcc.exe: fatal error: no input files
```

You may want to use [cmd version](https://paste.ee/p/dXNnR) of the batch if \`msys.bat' creates horribly looking terminal.
