### ISSUE TITLE
BadSeeds test performs redundant checking of seeds

### ISSUE THREAD

**Issue by eaglgenes101** [rurban/smhasher#225]
Right now, the hash function interface provided by SMHasher only provides 32 bits worth of seed. No more, no less. 

Not only do many keyed hash functions accept more than 32 bits worth of key, the BadSeeds test seems to assume that seeds are 64 bits, and thus the test ends up testing what effectively is the same 32-bit seed domain repeatedly. 

On a related note, there should be some way for a hash function to specify that it doesn't use a seed, so that seeding-based tests can be skipped for that hash function.

**Comment by rurban** [comment]
Yes, we know. Yves'fork provided larger seeds.
however this is for testing the hash functions, and we cannot really test such large seed ranges.

seed-independency is denoted by seed 0

**Comment by eaglgenes101** [comment]
> We cannot really test such large seed ranges.

Yes, that is correct. However, the seeds that _are_ checked is redundant. There are only 2^32 possible seeds, but the BadSeeds test checks 2^33 of them (the first 2^32 values, and the last 2^32 values). Pigeonhole principle tells us that there _must_ be some number of seeds that are being checked more than once. If you're restricting the hashes being tested to 32-bit seeds, the tests should at least reflect this.

**Comment by rurban** [comment]
We check the first 2^32 values, and the last 2^32 values only for 64bit hashes. 
For 32bit hashes we try all, without redundancies. 

Why only 32bit seeds: This is only a test artefact. The hashes usually take more, but realistically we can only test 32bit.
