### ISSUE TITLE
Support page doesn't load

### ISSUE THREAD

**Issue by strager** [rurban/smhasher#227]
When I visit the support page linked from smhasher's readme (<https://xscode.com/rurban/smhasher>), I see only the following:

> 403 Forbidden

Is the support page out of date? Is support no longer offered?

**Comment by rurban** [comment]
Interesting, they didn't tell me.
I'll check

strager ***@***.***> schrieb am Mo., 1. Aug. 2022, 21:16:

**Comment by rurban** [comment]
Well, they seem to be dead. I removed it.
