### ISSUE TITLE
Bugfix reminder, and request for linking to SMHasher3 fork

### ISSUE THREAD

**Issue by fwojcik** [rurban/smhasher#228]
Hello! I have emailed you a few times in the past, but only received a brief response once. I see you are more active on this project these days, so I am reaching out to you here.

Previously, I have noticed some serious bugs and some other areas that I thought were worth fixing up in smhasher. I put together a preliminary set of patches for you at https://gitlab.com/fwojcik/smhasher-rurban-fork/-/commits/fwojcik-fixes-bundled-public. They are still available, although the baseline is a bit outdated. I could rebase them on a later master if you need. As I said before, I **really** hate using Github or I'd have just done PRs here.

However, I ended up just fixing and changing more and more things, and I've ended up with my own fork of smhasher. While there is a copy on Github for convenience, the main site is on Gitlab. If you would please add a link to SMHasher3 at https://gitlab.com/fwojcik/smhasher3 in the README here, I would really appreciate it. Thank you!

**Comment by rurban** [comment]
Ah, interesting, I had no idea about those improvements

**Comment by rurban** [comment]
So I've looked through it, and most if it is very good. But the blocker to add your patches are that your patches are all GPL'd, not with the original MIT LICENSE.
So I'll rather just add a link.

**Comment by fwojcik** [comment]
Thank you! I appreciate it.

And I'm sorry for not being clearer. While SMHasher3 is GPL'd, I submitted all of those patches under the MIT license with the goal of having them in your distro. This was all done _long_ before I'd thought about running my own fork. I had been strenuously avoiding Github, which I've now (very sadly) started to work with again for other reasons. So I will shortly create PRs for most of the issues in that repo of fixes. If you don't want any or all of them, that's totally fine; you can just close the PRs and I'll drop it.

**Comment by rurban** [comment]
Yes, that's clear . I took all your patches from the fork (and PR's), bit none from smhasher3.

testing just needs a few days.
