### ISSUE TITLE
strange or incorrect results in REAME.md

### ISSUE THREAD

**Issue by leo-yuriev** [rurban/smhasher#24]
Seems here a set of mistakes:

1. md5 and sha1 looks miserably
    md5_32a == 8589.93x collisions, distrib
    sha1_32a == collisions, 36.6% distrib
    Sure this could be truth, but a sign error in the code and/or in the test.

2. falkhash result too much differs from local testing.
    Scores 39817.46, but my actual local test (i7-6700K) shows only 8909.54 MiB/Sec.
    For reference, t1ha_aes (properly optimized) shows 34867.98.

3. results of functions that uses SSE4.2 CRC32C also notable differs from my local testing.
    CityCrc128: 21009.15 vs local 14807.96.
    t1ha_crc:  16757.73 vs local 19237.25.
    metrohash128crc_1: 27790.85 vs local 21289.30.

**Comment by rurban** [comment]
The abbrevated versions of MD5 and SHA1 are indeed doing horribly, means their lower 32bits are not worth using. This is normal and also known from PRF (pseudo random functions), the higher bits are always best, lower bits are pretty bad.

See the doc/* directory for the full results: 

e.g. `doc/md5_32a` 
```
[[[ Keyset 'Seed' Tests ]]]

Keyset 'Seed' - 1000000 keys
Testing collisions   - Expected   116.42, actual 999999.00 (8589.93x) !!!!!
Testing distribution - Worst bias is the  17-bit window at bit   0 - 99.999% !!!!!
```

I haven't yet updated the speed tests, as I was out of the country. Need my stable machine for that.
Will do. I'm using a Haswell i7. Those SSE functions are *very* HW dependent.

**Comment by leo-yuriev** [comment]
Thanks for fast response.

-----------------------------

> I'm using a Haswell i7. Those SSE functions are very HW dependent.
I think circumstances (CPU, compiler version, optimization flags) of the testing should be noted in the results.

However, the results falkhash look suspicious. 
More over:
 -  Currently first (weak) version on falkhash is included.
    In general this version have problems with tests like sparse-bits.
    I think these problems are not detected in SMHasher only because falkhash uses the 0x50 block size, e.g. not a power of 2.
 - The fixed (second) version of falkhash expected to be significantly slower.

-----------------------------

> The abbrevated versions of MD5 and SHA1 are indeed doing horribly, means their lower 32bits are not worth using. This is normal and also known from PRF (pseudo random functions), the higher bits are always best, lower bits are pretty bad.

Hm...

```
./SMHasher sha1_32a
-------------------------------------------------------------------------------
--- Testing sha1_32a "SHA1, first 32 bits of result"

[[[ Sanity Tests ]]]

Verification value 0xF9376EA7 : PASS
Running sanity check 1    ..........FAIL  !!!!!
Running AppendedZeroesTest..........PASS
```

```
> git show --oneline
92b69f0 Merge pull request #23 from leo-yuriev/master
```

**Comment by leo-yuriev** [comment]
I tried to replace the implementation of SHA1.
The result is - a basic test ceased to fail, and the verification value was changed.

I will make a pull-request.

**Comment by rurban** [comment]
Oh, SHA1 must be stable.

**Comment by Bulat-Ziganshin** [comment]
>The abbrevated versions of MD5 and SHA1 are indeed doing horribly, means their lower 32bits are not worth using. This is normal and also known from PRF (pseudo random functions): The higher bits are always best, lower bits are pretty bad.

this is a big misunderstanding. some extremely simple hash function, that employs only mul/add, are indeed collect entropy in their higher bits. anything more complex, like t1ha-32 or xxh32, mixes entropy over the entire result

cryptohashes such as md4/md5/sha1 perfroms hundreds of mixing operations per input word and deliver results with highest quality of EVERY bit. I use 32-bit sha1 parts as ideal hash quality and you can see that all 4 parts i tested provides the same results, not worse than any other 32-bit hash:

https://github.com/Bulat-Ziganshin/FARSH/blob/master/SMHasher/reports/sha1_32.txt


The same applies to other 64+ bit hashes, f.e. this is testing of 32-bit SpookyHash quarters:

https://github.com/Bulat-Ziganshin/FARSH/blob/master/SMHasher/reports/Spooky32.txt


>This is normal and also known from PRF (pseudo random functions): The higher bits are always best, lower bits are pretty bad.


fuinally, PRG is just a hash function with parameter (seed). And hash quality doesn't depend on having the seed. The test you are referring to is just checked that 10-bit hash value can be discovered after 2^10 tries, that's not much surprise :)  And of course, it doesn't depend whether you use high or low hash bits
