### ISSUE TITLE
Am I an idiot or... does GOOD has FAILS but POOR has none in this case?

### ISSUE THREAD

**Issue by crisdosyago** [rurban/smhasher#242]
Hi @rurban I know you're busy and hope you're doing well! Thank you for your help in the past. Good to see your maintenance and extension of smhasher has contributed a lot of good stuff!

I had a question regarding two older hashes I submitted:

- [tifuhash](https://github.com/rurban/smhasher/blob/59f2ee39c7ceeae8106a59fbda5650c849d9e535/tifuhash.cpp) [results - no FAIL but rated POOR](https://github.com/rurban/smhasher/blob/59f2ee39c7ceeae8106a59fbda5650c849d9e535/doc/tifuhash_64.txt), and
- [floppsyhash](https://github.com/rurban/smhasher/blob/59f2ee39c7ceeae8106a59fbda5650c849d9e535/floppsyhash.cpp) [results - many FAIL but rated GOOD](https://github.com/rurban/smhasher/blob/master/doc/floppsyhash.txt)

you've probably told me the reason for this before and I've just forgotten, but would it be a bad idea for you to tell me why the results with no fail say GOOD, but the results with many fail so POOR?

**Comment by rurban** [comment]
Thanks for notifying me. Recently lots of tests were improved, and I didn't reclassify all hashes.

**Comment by crisdosyago** [comment]
@rurban no worries mate! Hope you're well and enjoy the rest of your year! ☺️

**Comment by rurban** [comment]
Use `testgood-but-poor.sh` and `testpoor-but-good.sh`

**Comment by rurban** [comment]
Now fixed. Sorry. You are GOOD again :)
