### ISSUE TITLE
Recent Ryzen 5 3350G 3.6GHz speed tests

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#252]
Hi! I'd like to know which compiler and options were used to run the speed tests, specifically related to `komihash`. The bulk speed of just 12.3 GB/s on 3.6-4GHz (single thread) Zen+ processor looks unbelievable to me. It should be at least 18 GB/s. `komihash` uses the same underlying 128-bit result multiplications as `wyhash`, in my tests on different computers and compilers I get maybe 20% advantage of wyhash. `komihash` was also extensively tested as part of eBASH benchmark: https://bench.cr.yp.to/results-hash.html (take a look at rumba7 machine)

**Comment by rurban** [comment]
It must have been g++12 I think

**Comment by avaneev** [comment]
But what compiler options were?

**Comment by rurban** [comment]
None

**Comment by avaneev** [comment]
Could you please run `gcc -v` and an post output here?

**Comment by rurban** [comment]
Only when I'm back at my work machine, after the holidays
