### ISSUE TITLE
prvhash

### ISSUE THREAD

**Issue by avaneev** [rurban/smhasher#275]
Please update the speeds of all presented prvhash hashes. The latest update includes "always_inline" attribute like in the recent "komihash" update. Maybe that can make a difference. There was also a change to function parameters (no InitVec is available now).

**Comment by rurban** [comment]
done

**Comment by avaneev** [comment]
Suspicious that previously it was 260.27 cycles and now its 361.73 cycles for the same code? But I won't be playing your game, your karma is your responsibility. Same applies for komihash speeds.

**Comment by avaneev** [comment]
The code of prvhash64_64m() was actually reverted to v4.3 when it had even lower timings per your test - 241.19 (cycl./map). Personal bias is definitely at play, that's without doubt now.

**Comment by rurban** [comment]
looks like the recent amd firmware patches slowed everything down. On Intel also.
Would need a full test speed update for all. I'll try this over the weekend, but then I'd need to disable all cronjobs

**Comment by avaneev** [comment]
Hmm? Zenbleed affects Zen2 processors only, and komihash timings did not increase by 100... Just saying.

**Comment by avaneev** [comment]
Thanks.
