### ISSUE TITLE
Add modern HighwayHash from Google

### ISSUE THREAD

**Issue by leo-yuriev** [rurban/smhasher#28]
https://github.com/google/highwayhash

**Comment by leo-yuriev** [comment]
@jan-wassenberg, could you make a pull request to this SMHasher ?

**Comment by Bulat-Ziganshin** [comment]
afaik, they don't have smhasher binfing. instead, they ripped a single test, increased repetition count and made incorrect conclusion based on the single random run. again, read the paper and check their issues section - i wrote about that

**Comment by rurban** [comment]
FYI: This is in the same ballpark as chaskey, another siphash improvement. Needs a bit of work.

**Comment by cup** [comment]
https://github.com/cmuratori/meow_hash/issues/1

**Comment by rurban** [comment]
Working on it in the branch `highway`
Just don't know yet if we should just use the avx2 variant or the full portable solution

**Comment by rurban** [comment]
Added with b778af623d1cedcd00f62943b670b15124d4c7e6 probing and using the external library, using the portable version, which has some run-time cpuid overhead. The highway branch has the attempt to use the faster native version for sse4.1. But it's still the 2nd slowest of all good hashes, so I don't bother that much. PR's appreciated.
