### ISSUE TITLE
Add FARSH

### ISSUE THREAD

**Issue by leo-yuriev** [rurban/smhasher#29]
Add FARSH from https://github.com/Bulat-Ziganshin/FARSH

@Bulat-Ziganshin, could you make a pull-request?

Let me explain.
I want to get the one SMHasher in a single place, with the set of almost of all modern hashes.
And then make it (SMHasher) better...

**Comment by Bulat-Ziganshin** [comment]
1. i want the same
2. current farsh isn't finished and seems to have a bug (see Issues)

**Comment by rurban** [comment]
Agreed. Waiting for https://github.com/Bulat-Ziganshin/FARSH/issues/4 to be resolved first

**Comment by rurban** [comment]
I'm adding it now, to get the proper tests published.

**Comment by Bulat-Ziganshin** [comment]
AppendedZeroes should be fixed by removing one line. AFAIR, at the time of development it passed all tests, so it's great if new tests can show its weakness
