### ISSUE TITLE
gxhash does not build on older x86-64 CPUs

### ISSUE THREAD

**Issue by chadaustin** [rurban/smhasher#304]
Running ./build.sh on my Atom D2700 hits https://github.com/rurban/smhasher/blob/b081a0ad4d4c51642a98a568dcee4b3922a94bad/gxhash.c#L249 and the rest of the file fails to compile.

Looks like CMakeLists.txt attempts to skip gxhash if AES extensions are not supported, but gxhash.c is still included in the build.

**Comment by rurban** [comment]
@ogxd
