### ISSUE TITLE
add comparison for 32bit CPUs

### ISSUE THREAD

**Issue by wizzard0** [rurban/smhasher#37]
performance is important on small embedded devices too :)

**Comment by rurban** [comment]
sure, but I don't have such 32bit hardware. I don't have a native raspberry pi nor setup a phone sdk.
you are welcome to provide such numbers, pull requests welcome.

**Comment by rurban** [comment]
I added now benchmark tables for other machines, so the infrastructure is there.
I could publish a `gcc -m32` benchmark on i686 at least.

**Comment by rurban** [comment]
done some time ago
https://rurban.github.io/smhasher/doc/i686.html
