### ISSUE TITLE
Broken crc64_hw1 link in README.md

### ISSUE THREAD

**Issue by akopytov** [rurban/smhasher#42]
The crc64_hw1 link in README.md points to a non-existing page: https://github.com/rurban/smhasher/blob/master/doc/crc64_hw1

It's most likely supposed to point to https://github.com/rurban/smhasher/blob/master/doc/crc32_hw1. And then a separate line is required for https://github.com/rurban/smhasher/blob/master/doc/crc64_hw

**Comment by rurban** [comment]
Oops, thanks. I thought I created those links automatically. Apparently not.
