### ISSUE TITLE
Massive difference in reported performance

### ISSUE THREAD

**Issue by paulie-g** [rurban/smhasher#46]
I have a fork from some time in late 2015, which I used to add a c implementation of metrohash and a version with some optimizations for shorter keys. I kept the fork after the pull request was accepted upstream, here.

I've now tried the latest master and, besides what i reported in #45 , I am seeing massive differences in reported performance. For cmetrohash64_1, I am seeing:

```
--- my old fork (old build) ---
[[[ Speed Tests ]]]

Bulk speed test - 262144-byte keys
Alignment  7 -  4.087 bytes/cycle - 11694.32 MiB/sec @ 3 ghz
Alignment  6 -  4.087 bytes/cycle - 11694.35 MiB/sec @ 3 ghz
Alignment  5 -  4.088 bytes/cycle - 11694.78 MiB/sec @ 3 ghz
Alignment  4 -  4.087 bytes/cycle - 11691.98 MiB/sec @ 3 ghz
Alignment  3 -  4.087 bytes/cycle - 11692.93 MiB/sec @ 3 ghz
Alignment  2 -  4.088 bytes/cycle - 11695.01 MiB/sec @ 3 ghz
Alignment  1 -  4.087 bytes/cycle - 11693.52 MiB/sec @ 3 ghz
Alignment  0 -  4.214 bytes/cycle - 12057.15 MiB/sec @ 3 ghz
Average      -  4.103 bytes/cycle - 11739.26 MiB/sec @ 3 ghz

Small key speed test -    1-byte keys -    25.03 cycles/hash
Small key speed test -    2-byte keys -    22.72 cycles/hash
Small key speed test -    3-byte keys -    24.72 cycles/hash
Small key speed test -    4-byte keys -    23.93 cycles/hash
Small key speed test -    5-byte keys -    24.81 cycles/hash
Small key speed test -    6-byte keys -    31.58 cycles/hash
Small key speed test -    7-byte keys -    33.89 cycles/hash
Small key speed test -    8-byte keys -    24.33 cycles/hash
Small key speed test -    9-byte keys -    24.08 cycles/hash
Small key speed test -   10-byte keys -    24.59 cycles/hash
Small key speed test -   11-byte keys -    26.19 cycles/hash
Small key speed test -   12-byte keys -    24.89 cycles/hash
Small key speed test -   13-byte keys -    25.67 cycles/hash
Small key speed test -   14-byte keys -    32.87 cycles/hash
Small key speed test -   15-byte keys -    32.59 cycles/hash
Small key speed test -   16-byte keys -    25.20 cycles/hash
Small key speed test -   17-byte keys -    35.00 cycles/hash
Small key speed test -   18-byte keys -    33.86 cycles/hash
Small key speed test -   19-byte keys -    36.35 cycles/hash
Small key speed test -   20-byte keys -    33.22 cycles/hash
Small key speed test -   21-byte keys -    35.64 cycles/hash
Small key speed test -   22-byte keys -    34.87 cycles/hash
Small key speed test -   23-byte keys -    37.67 cycles/hash
Small key speed test -   24-byte keys -    28.85 cycles/hash
Small key speed test -   25-byte keys -    36.54 cycles/hash
Small key speed test -   26-byte keys -    35.79 cycles/hash
Small key speed test -   27-byte keys -    37.79 cycles/hash
Small key speed test -   28-byte keys -    36.27 cycles/hash
Small key speed test -   29-byte keys -    36.64 cycles/hash
Small key speed test -   30-byte keys -    36.64 cycles/hash
Small key speed test -   31-byte keys -    36.45 cycles/hash
Average                                    29.959 cycles/hash
---

--- my old fork (new build) ---
[[[ Speed Tests ]]]

Bulk speed test - 262144-byte keys
Alignment  7 -  4.282 bytes/cycle - 12252.21 MiB/sec @ 3 ghz
Alignment  6 -  4.282 bytes/cycle - 12250.16 MiB/sec @ 3 ghz
Alignment  5 -  4.282 bytes/cycle - 12251.42 MiB/sec @ 3 ghz
Alignment  4 -  4.282 bytes/cycle - 12251.76 MiB/sec @ 3 ghz
Alignment  3 -  4.282 bytes/cycle - 12251.84 MiB/sec @ 3 ghz
Alignment  2 -  4.283 bytes/cycle - 12253.69 MiB/sec @ 3 ghz
Alignment  1 -  4.283 bytes/cycle - 12253.13 MiB/sec @ 3 ghz
Alignment  0 -  4.477 bytes/cycle - 12808.42 MiB/sec @ 3 ghz
Average      -  4.307 bytes/cycle - 12321.58 MiB/sec @ 3 ghz

Small key speed test -    1-byte keys -    28.09 cycles/hash
Small key speed test -    2-byte keys -    28.04 cycles/hash
Small key speed test -    3-byte keys -    23.64 cycles/hash
Small key speed test -    4-byte keys -    22.84 cycles/hash
Small key speed test -    5-byte keys -    23.91 cycles/hash
Small key speed test -    6-byte keys -    25.69 cycles/hash
Small key speed test -    7-byte keys -    43.28 cycles/hash
Small key speed test -    8-byte keys -    27.13 cycles/hash
Small key speed test -    9-byte keys -    23.84 cycles/hash
Small key speed test -   10-byte keys -    23.90 cycles/hash
Small key speed test -   11-byte keys -    23.87 cycles/hash
Small key speed test -   12-byte keys -    23.09 cycles/hash
Small key speed test -   13-byte keys -    25.49 cycles/hash
Small key speed test -   14-byte keys -    26.53 cycles/hash
Small key speed test -   15-byte keys -    27.38 cycles/hash
Small key speed test -   16-byte keys -    26.85 cycles/hash
Small key speed test -   17-byte keys -    28.03 cycles/hash
Small key speed test -   18-byte keys -    28.09 cycles/hash
Small key speed test -   19-byte keys -    28.64 cycles/hash
Small key speed test -   20-byte keys -    28.61 cycles/hash
Small key speed test -   21-byte keys -    28.78 cycles/hash
Small key speed test -   22-byte keys -    29.31 cycles/hash
Small key speed test -   23-byte keys -    29.46 cycles/hash
Small key speed test -   24-byte keys -    26.75 cycles/hash
Small key speed test -   25-byte keys -    29.50 cycles/hash
Small key speed test -   26-byte keys -    30.41 cycles/hash
Small key speed test -   27-byte keys -    31.03 cycles/hash
Small key speed test -   28-byte keys -    30.18 cycles/hash
Small key speed test -   29-byte keys -    31.50 cycles/hash
Small key speed test -   30-byte keys -    32.22 cycles/hash
Small key speed test -   31-byte keys -    40.30 cycles/hash
Average                                    27.386 cycles/hash
---

--- master ---
[[[ Speed Tests ]]]

Bulk speed test - 262144-byte keys
Alignment  7 -  4.284 bytes/cycle - 12255.87 MiB/sec @ 3 ghz
Alignment  6 -  4.283 bytes/cycle - 12253.74 MiB/sec @ 3 ghz
Alignment  5 -  4.283 bytes/cycle - 12254.33 MiB/sec @ 3 ghz
Alignment  4 -  4.284 bytes/cycle - 12256.09 MiB/sec @ 3 ghz
Alignment  3 -  4.283 bytes/cycle - 12254.51 MiB/sec @ 3 ghz
Alignment  2 -  4.284 bytes/cycle - 12255.59 MiB/sec @ 3 ghz
Alignment  1 -  4.283 bytes/cycle - 12254.99 MiB/sec @ 3 ghz
Alignment  0 -  4.500 bytes/cycle - 12875.79 MiB/sec @ 3 ghz
Average      -  4.311 bytes/cycle - 12332.61 MiB/sec @ 3 ghz

Small key speed test -    1-byte keys -    25.00 cycles/hash
Small key speed test -    2-byte keys -    25.00 cycles/hash
Small key speed test -    3-byte keys -    31.00 cycles/hash
Small key speed test -    4-byte keys -    25.00 cycles/hash
Small key speed test -    5-byte keys -    30.00 cycles/hash
Small key speed test -    6-byte keys -    30.00 cycles/hash
Small key speed test -    7-byte keys -    36.00 cycles/hash
Small key speed test -    8-byte keys -    35.00 cycles/hash
Small key speed test -    9-byte keys -    40.00 cycles/hash
Small key speed test -   10-byte keys -    40.00 cycles/hash
Small key speed test -   11-byte keys -    46.00 cycles/hash
Small key speed test -   12-byte keys -    40.00 cycles/hash
Small key speed test -   13-byte keys -    45.88 cycles/hash
Small key speed test -   14-byte keys -    46.00 cycles/hash
Small key speed test -   15-byte keys -    52.00 cycles/hash
Small key speed test -   16-byte keys -    39.00 cycles/hash
Small key speed test -   17-byte keys -    45.00 cycles/hash
Small key speed test -   18-byte keys -    45.00 cycles/hash
Small key speed test -   19-byte keys -    50.46 cycles/hash
Small key speed test -   20-byte keys -    45.00 cycles/hash
Small key speed test -   21-byte keys -    50.00 cycles/hash
Small key speed test -   22-byte keys -    50.99 cycles/hash
Small key speed test -   23-byte keys -    56.00 cycles/hash
Small key speed test -   24-byte keys -    45.00 cycles/hash
Small key speed test -   25-byte keys -    50.00 cycles/hash
Small key speed test -   26-byte keys -    50.82 cycles/hash
Small key speed test -   27-byte keys -    56.00 cycles/hash
Small key speed test -   28-byte keys -    51.00 cycles/hash
Small key speed test -   29-byte keys -    56.00 cycles/hash
Small key speed test -   30-byte keys -    57.00 cycles/hash
Small key speed test -   31-byte keys -    62.00 cycles/hash
Average                                    43.747 cycles/
---
```

I started going through the 100 or so commits before now and then to try to figure out where this comes from, but finally decided it was quicker to ask ;)

As you can see, increase in throughput is the same for my old snapshot and current master if built with my current gcc 8.1.1. At least that's where it looks to be coming from. The difference in cycles/hash must be a result of something introduced since then. Has the way you count cycles fundamentally changed?

**Comment by paulie-g** [comment]
Cheers for the response mate. You wouldn't happen to be able to point me to the issue/pull request/commits for that? If not, I'll go trawling myself ;)

You see, there's still a bit of a mystery - if all of the hash functions now measured at some y = x * old_cycles_per_hash, where x is relatively constant, it'd all be clear. However, my cmetrohash64 implementation optimized for short keys (taken from my old fork, since the in-tree implementation got clobbered) now measures as almost the same on average as the unoptimized cmetrohash it's built on *and* exhibits bizarre spikes in cycles/hash at certain key lengths, which it didn't do before.

I need to understand why that is so. Either my optimization is and was garbage, but just so happened to somehow take advantage of the previous (presumably inferior) measurement method, or one (or more) of the measurement algo changes, compiler flag changes and compiler upgrade have done this.

**Comment by rurban** [comment]
I'll first fix the 32bit regressions, and then look into this one. 
jody64 on 32bit was the culprit. This needs to be added to the smoker tests to catch bad PR's.

**Comment by paulie-g** [comment]
I've tracked this down to #15 

The off-by-one error fix is correct, so that's a multiplier of x = (32/31). Well caught.

I'm not at all sure about the rest of the PR. @vegorov1 is correct in that we want to measure things lexically between the opening and the closing RDTSC and don't want things re-ordered into or out of there. The PR doesn't do that, instructions from inside the measurement can be executed during the opening RDTSC and instructions following the closing RDTSC can be executed before it. This needs some lfences or CPUID or some other barriers.

Moreover, I am not at all certain that I agree that we should be clobbering pipelining. Unless our intended use case for the hash functions is to run them on an in-order architecture, pipelining is important and useful - if we didn't care about it, we could just go through the machine code with op code handbook in hand and count the cycles. Forcing serial execution doesn't fix our measurements, it simply distorts them in another direction.

Current master yields an average ~129 cycles/hash for falkhash, for example, but ~98 with this change backed out. This is purely because it's being penalized for the latency of instructions used in a way that would never happen in real code. The same applies to other hashes, like metro and the t1ha variant I tested, that are well-behaved wrt pipelining.

I agree that the case where we allow full pipelining on successively called hash functions under test is a bit optimistic, but so is running successive trials with the same length key, which advantages hash functions whose performance depends on good branch prediction for example.

Fundamentally, I very much disagree with replacing an existing speed testing mode with one that drastically alters the conditions and isn't any more correct, but rather "differently broken". Adding it as an additional speed testing mode would be fine and indeed beneficial, but this sort of drive-by yanking out of continuity in comparability is counterproductive imho.

**Comment by rurban** [comment]
I also said that we need an lfence or cpuid instruction for better measurement sooner or later, but we don't have it yet. The current measurement is better, but still not optimal. Esp. since it completes neglects practical issues for usage in a hash table, where the small functions are much faster than the big and here faster functions. I haven't even yet added a measurement method for this icache phenomenon, e.g. the object size or cachegrind results.
