### ISSUE TITLE
Add some more hash funcs

### ISSUE THREAD

**Issue by rurban** [rurban/smhasher#5]
https://code.google.com/p/crcutil/ has some efficient (in fact the currently most efficient) funcs. multiword_128_64_gcc_amd64_sse2

http://www.strchr.com/hash_functions lists some FNV1 based improvements and more, with a good quality check from the dragon book. 
https://github.com/gpnuma/fsbench-density.git could be imported as submodule.
esp. Jesteress, Meiyan, YoshimitsuTRIAD, Tesla, ...
and they (fsbench) have also all the new secure hashes.

CityHash32 (without seed, but can be added. I wrote one)

fletcher2,4 from ZFS

I wrote also the  metrohash64crc_1,2 variants, but with too many collisions in one test so far.

sse4.2 run-time probing can be added into main, to see if the target can run the version which was configured.

**Comment by rurban** [comment]
Added some more useful variants, just fletcher, crypto and some FNV variants are missing.

**Comment by nordin** [comment]
Another interesting hash is FastHash64: https://code.google.com/p/fast-hash/

**Comment by uxcn** [comment]
If you're interested, I just uploaded a full C99 translation of [FarmHash](https://github.com/uxcn/farmhash-c).

**Comment by Bulat-Ziganshin** [comment]
There is also CLHash and my FARSH. FARSH seems to be fastest in town - once you have AVX2 cpu :)
https://github.com/lemire/clhash
https://github.com/Bulat-Ziganshin/FARSH#benchmark

**Comment by rurban** [comment]
Added 2 SipHash variants, but not the faster Google TreeHash. 
chaskey (also a variant) is in a branch, and needs a few fixes.

**Comment by rurban** [comment]
crcutil is in the zlib branch, the rest is done already
