### ISSUE TITLE
wyhash

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#53]
Dear Author:
   I developed a new hash function that passed all your tests. It is the fastest one for short keys, faster than t1ha. Since I am new to github, just let you known it from this way. It is located at https://github.com/wangyi-fudan/wyhash

**Comment by rurban** [comment]
Oh nice, I'll test it and include it  if it really does what you said.
Thanks

WangYi <notifications@github.com> schrieb am Mi., 6. März 2019, 08:05:

**Comment by wangyi-fudan** [comment]
yes, I only focus on 64bit little end-in machines. Previously, I used t1ha, however, it gets fatter and fatter to be compatible with everything.

**Comment by wangyi-fudan** [comment]
Hi, i removed the dependence of stdint.h
