### ISSUE TITLE
Running extended tests

### ISSUE THREAD

**Issue by Cyan4973** [rurban/smhasher#56]
I've been using this great fork of SMHasher to validate a new hash algorithm,
and in the process, I found it useful to push the tests to higher limits.

The reason is, most tests are designed around "small" input length, in order to scout a tractable search space. Unfortunately, many modern hash algorithms feature different code paths depending on the input size. As a consequence, path for large input length is not stressed enough, which makes it possible to "pass" the tests, while they were effectively skipped.

Another factor is that computing capacity has increased a lot since SMHasher initial release, and it's now less problematic to run and analyse many more results per test.

I've implemented these changes in a fork at [Cyan4973/SMHasher](https://github.com/Cyan4973/smhasher). I was wondering if you would be interested in such changes, and if yes, if you have some PR-related requirements, for example around patch size.

**Comment by rurban** [comment]
Sure, I've already looked at your changes last week and liked the overall ideas, but then it was still a little but rough.

**Comment by Cyan4973** [comment]
I agree. I can spend time to make these changes more acceptable for a PR.

**Comment by Cyan4973** [comment]
#57

**Comment by rurban** [comment]
#57 was merged, thanks Yann!
