### ISSUE TITLE
wyhash update

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#59]
Dear rurban:
  wyhash have been updated significantly with the "threat" of XXH3. The cycles per hash have been reduced by 1.5 on average. The long key speed is much higher. Also portability has been improve due to aligned read. cheers!

**Comment by wangyi-fudan** [comment]
now the cycles have been reduced by 50%! benchmark it or you won't believe it!

**Comment by rurban** [comment]
Yes, I tried already. I just need to merge it with my windows fixes

**Comment by rurban** [comment]
Done with f2b35ad5ae3ce6bae7774f8951c8466a9f8ff12e
