### ISSUE TITLE
Add more realistic Text HashTable tests

### ISSUE THREAD

**Issue by rurban** [rurban/smhasher#61]
Find the distribution of the most common chars in programming language names (ean...)
Test against randomly generated names from those with typical short lengths (see rurban/perl-hash-stats).

And test a more common hash table speed scenario (I-Cache), 
to verify why FNV1A and Spooky32 are so much better there than the others.

**Comment by rurban** [comment]
Also see Yann's new benchmark suite for xxh3: https://github.com/Cyan4973/xxHash/tree/dev/tests/bench

**Comment by dumblob** [comment]
>Also see Yann's new benchmark suite for xxh3: https://github.com/Cyan4973/xxHash/tree/dev/tests/bench

Oh, I'm sorry, that's the one I meant in all my comments in other threads (didn't notice it's still just in the dev branch).

@sanmayce @wangyi-fudan please note the linked Yann's benchmark from my comments seems to be the old one, but I actually meant the new one which sits in the `dev` branch. Feel free to take a look.

**Comment by Sanmayce** [comment]
It's confusing, I took the bench suite from the latest 'xxHash-0.7.2.zip' from October, what makes this 'dev' more interesting, it is much older?

**Comment by dumblob** [comment]
@Sanmayce can't tell about the release archive, but the current master<->dev branch doesn't differ much - see https://github.com/Cyan4973/xxHash/compare/master...dev

**Comment by rurban** [comment]
the benchmarks are the same: https://github.com/Cyan4973/xxHash/compare/v0.7.2...dev

**Comment by rurban** [comment]
Merged branch HashMapTest with b1ad36aaf820cb5d267500c270e0bd3fb2195aa0
