### ISSUE TITLE
wyhash bug fixed

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#64]
Dear rurban:
  Tommy Ettinger fixed a bug in wyhash which cause avalanche failure in 136 bit. wyhash have been updated. (I updated too quickly, sorry to trouble you frequently :-)

**Comment by rurban** [comment]
No problem, you can bug me all the time. Pull requests would be even better, but first you need to learn some git :) No problem for me

**Comment by rurban** [comment]
These changes since wyhash_version 20190320 broke the tests for wyhash32low, the lower 32bits.

**Comment by wangyi-fudan** [comment]
all bugs fixed, including 136 bit avalanche and 32bit low bits at the cost of some speed loss. But much stronger for future tests!

**Comment by wangyi-fudan** [comment]
Just a bit confused. It seem that rwyhash 32bit is not bad? I just made a safer version if it does broken.

**Comment by rurban** [comment]
on MSVC 32bit we get: `error C3861: '_umul128': identifier not found `

**Comment by rurban** [comment]
Fixed with 8336f266090f08f35bf2e26688128493f8b5022b and b38d31cf3e5b6763aa96edd19f3de1120b41328a
