### ISSUE TITLE
something wrong with your xxh3 benchmark?

### ISSUE THREAD

**Issue by hiqbn** [rurban/smhasher#68]
it's showing 40k+ compared with metrohash

my test shows metrohash to be faster by a bit than xxh3

can u confirm the results you published?

**Comment by rurban** [comment]
I run it either on darwin, with a much better libc than glibc (haswell optimized), and a i7-4650U and clang, or on debian, with an older i5-2300 on gcc.

The libc and the compiler, esp. memcpy and memcmp, do make a big difference, +- 10%.
This time I ran it on linux.

**Comment by hiqbn** [comment]
pls do mention this inside main. thx

**Comment by hiqbn** [comment]
pls do mention this inside main. thx
