### ISSUE TITLE
Add ktprime hashes

### ISSUE THREAD

**Issue by dumblob** [rurban/smhasher#71]
https://github.com/ktprime/ktprime

**Comment by rurban** [comment]
I don't see any new hash function there

**Comment by dumblob** [comment]
You're right, there is only one and it's quite hidden - https://github.com/ktprime/ktprime/blob/master/hash_table6.hpp#L1489 (refers to *"Thomas Wang's function"* https://gist.github.com/badboy/6267743 ).

**Comment by rurban** [comment]
dumblob <notifications@github.com> schrieb am Sa., 6. Juli 2019, 21:14:

> You're right, there is only one and it's quite hidden -
> https://github.com/ktprime/ktprime/blob/master/hash_table6.hpp#L1489
> (refers to *"Thomas Wang's function"*
> https://gist.github.com/badboy/6267743 ).
>

Yes, this gist is the useful one. Could be added to the bad functions. Not
particularly fast also.

**Comment by rurban** [comment]
This is only for 32 and 64bit integers or pointers, without seed. Sorry, no
