### ISSUE TITLE
Crypto tests. Q: Are you sure? ("secure quality crypto hash functions are actually statistically extremely weak")

### ISSUE THREAD

**Issue by leo-yuriev** [rurban/smhasher#87]
The probability of such errors is quite small, and if such flaws really exist, then all these functions cannot be recognized as cryptographically strong. So either you've found a way to attack all modern cryptography, or there's a trivial bug in smhasher.

I will definitely check the code, but (unfortunately) I will not be able to do it until the weekend.

**Comment by rurban** [comment]
I'm sure about the failing tests and the weakness, but I'm not sure about the cryptographic applicability. 
It involves changes in the worst 32bit state word (the seed), which is not used and tested in crypto. In my understanding weak state mixings point to a weak function. Crypto deals with weak keys or timing, the state is fixed.

**Comment by leo-yuriev** [comment]
@Cyan4973?

**Comment by wangyi-fudan** [comment]
I think it's a bug.

```C
static	inline	void	wysha(const	void	*key,	int	len,	unsigned	seed,	void *out) {
	uint64_t	s[4]={wyhash(key,len,seed+0),wyhash(key,len,seed+1),wyhash(key,len,seed+2),wyhash(key,len,seed+3)};
	memcpy(out,	s,	32);
}
```

```
Keyset 'Sparse' - 32-bit keys with up to 7 bits set - 4514873 keys
Testing collisions (256-bit)     - Expected          0.0, actual      0 (0.00x)
Testing collisions (high 128-bit) - Expected          0.0, actual      0 (0.00x)
Testing collisions (high 64-bit) - Expected          0.0, actual      0 (0.00x)
Testing collisions (high 32-bit) - Expected       4746.0, actual   2386 (0.50x)
Testing collisions (high 26-39 bits) - Worst is 38 bits: 39/74 (0.53x)
Testing collisions (high 12-bit) - Expected    4514873.0, actual 4510777 (1.00x) (-4096)
Testing collisions (high  8-bit) - Expected    4514873.0, actual 4514617 (1.00x) (-256)
Testing collisions (low  128-bit) - Expected          0.0, actual 4514872 (75369200179260515463276265472000.00x) (4514872) !!!!!
Testing collisions (low  64-bit) - Expected          0.0, actual 4514872 (4085772528642.46x) (4514872) !!!!!
Testing collisions (low  32-bit) - Expected       4746.0, actual 4514872 (951.29x) (4510126) !!!!!
Testing collisions (low  26-39 bits) - Worst is 39 bits: 4514872/37 (121765.51x) !!!!!
Testing collisions (low  12-bit) - Expected    4514873.0, actual 4514872 (1.00x) (-1)
Testing collisions (low   8-bit) - Expected    4514873.0, actual 4514872 (1.00x) (-1)
Testing distribution - Worst bias is the 19-bit window at bit 38 - 0.064%

```

**Comment by rurban** [comment]
@wangyi-fudan In the new collisions test?

**Comment by rurban** [comment]
BTW: I will not merge this new CRYPTO README paragraph, until we can agree on it's interpretation and wording. Maybe it's just a test bug. Maybe the tests should emphasize more on the key and less on the seed, and leave the seed asis.

**Comment by wangyi-fudan** [comment]
> 
> 
> @wangyi-fudan In the new collisions test?

yes, I downloaded your lastest crypto branch. you can test it by yourself, super easy.

**Comment by leo-yuriev** [comment]
@rurban:
 - for Keccak it is correct to poke a seed into the `capacity` part of state, but NOT into the `rate` (since it is equals to XOR with a subsequent input).
 - for MD5, SHA1, SHA2 and BLAKE2b it is correct to poke a seed into any part of the state.

So, seems it is a bug in the test(s).

**Comment by rurban** [comment]
I agree with WangYi, the testLowBits part in `TestHashList` is broken. I wrote that, not Yann.

**Comment by rurban** [comment]
I've deleted now this obsolete CRYPTO paragraph, as I found and fixed the test bug. It was an underflow with hashtypes > 64bit, as operator |= was only defined for int, not anything larger, thus zeroextending it silently.
Updating the wrong tests will need a few days.
