### ISSUE TITLE
discussion: speed vs code size

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#89]
Hi,
I would like to know your opinion on speed vs code size tradeoff.
wyhash's key loop is 32 byte. however, in order to gain bulk speed, i manually expanded to 256 byte loop.
also wyhash has a quick 32 byte return, which is a bit faster for short key but not necessary.
do you need a minimal version or the faster (+30 bulk, +5% short key) version?

**Comment by rurban** [comment]
Personally I prefer short keys over bulk processing, i.e. shorter code size as in hash tables. 
But others might prefer bulk speed for larger data, i.e. file or database digests. xxh3 and t1ha clearly go into that direction.
Maybe provide two functions, one for shorter and one for larger keys. 
And for others maybe one for unaligned data also.
