### ISSUE TITLE
floppsyhash request

### ISSUE THREAD

**Issue by crislin2046** [rurban/smhasher#93]
Hi @rurban 

I discovered your SMHasher fork today.

Thank you for taking care of SMHasher.

Thanks for finding and adding tifuhash yourself

Noticed tifu was here and was failing some new tests.

I made an updated hash, that passes all the tests.

I call this new hash floppsyhash. It is based on tifu but different and new 

I'm sorry but would it be impossible for you to add this new hash newly under this name?

The link is here: https://github.com/crislin2046/floppsy

I know it's not your job to help some lazy guy with his super annoying request....

**Comment by rurban** [comment]
Not annoying at all. I'm glad to help. Will add the new one soon

**Comment by crislin2046** [comment]
You're awesome!

**Comment by rurban** [comment]
6x faster than tifuhash, (also tested on my fast machine). nice.
See my PR for a needed MSVC fix.

**Comment by crislin2046** [comment]
Thank you!
