### ISSUE TITLE
wyhash_v4 published

### ISSUE THREAD

**Issue by wangyi-fudan** [rurban/smhasher#96]
Dear All:
  I am happy to announce that with hard work during Chinese new year, wyhash_v4 is ready.
  features:
  big endian support (may have bugs as it hasn't been test on real mahines). 
  half code size. 
  faster short key hashing
  faster bulk key hashing
  cheers!

Since the V3 thread is full, I just trouble you by opening a new issue :-)

**Comment by rurban** [comment]
Already merged

**Comment by wangyi-fudan** [comment]
it is a bit newer...

**Comment by rurban** [comment]
Ah, OK.

**Comment by rurban** [comment]
Done. Indeed much faster

**Comment by wangyi-fudan** [comment]
a newer version of wyhash_v4 comes out, allow stream hash, a bit faster

corpus: /usr/share/dict/words
hash 		short key	hashmap	bulk16M
wyhash 		245.961	45.612	19.053
wyhash_old	241.616	44.990	18.686
XXH3_scalar	187.113	44.173	13.048
